### ISSUE TITLE
Add bomb sound effect

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#103]
The game currently has sound effects for attacking and healing, but no sound plays when the player uses a bomb. 

We'd like to use a sound effect like this to play when the player uses a bomb: https://freesound.org/people/Taira%20Komori/sounds/215595/

Please make sure you credit the original author in `Sound.cpp`!

**Comment by LaloCode** [comment]
Hello, I've been checking this project out and it seems interesting, would love to try my hand at adding this 😁

**Comment by tagniam** [comment]
@LaloCode Yeah sure, go for it! 🙂

**Comment by tagniam** [comment]
Closed by #109
