### ISSUE TITLE
Add whetstone sound effect

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#104]
The game currently has sound effects for attacking and healing, but no sound plays when the player uses a whetstone. 

We'd like to use a sound effect like this to play when the player uses a whetstone: https://freesound.org/people/GameDevC/sounds/422832/

Please make sure you credit the original author in `Sound.cpp`!

**Comment by Shaedil** [comment]
Hey, I'd like to give this a try if you don't mind.

**Comment by tagniam** [comment]
@Shaedil Go for it! :+1:
