### ISSUE TITLE
Embed sound files in game executable

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#111]
Currently we don't embed sounds in the game executable: the program expects a `sounds` folder in the same directory to play the sound files from. We'd like to change that, so that the sound files are embedded within the executable and would not require an external `sounds` folder.

The implementation should work across all platforms. One possible way to do this is to convert the sound files into byte array constants, but let me know of any other (possibly better) approaches!

**Comment by igorsegallafa** [comment]
Dont you like the solution where the files are copied to `bin` folder? Simply adding a command on CMake. I believe this is the easiest and simpler solution.

Embedding the binary of sound as byte array into C, would generate a huge array and would be necessary to save the byte array as a file, to `PlaySound` from Win32 read it properly.

**Comment by tagniam** [comment]
>Simply adding a command on CMake.

Which command are you referring to here, specifically?

**Comment by igorsegallafa** [comment]
> 
> 
> > Simply adding a command on CMake.
> 
> Which command are you referring to here, specifically?

Here: https://github.com/tagniam/Turn/pull/117
