### ISSUE TITLE
Use compiler warnings

### ISSUE THREAD

**Issue by bodand** [tagniam/Turn#118]
The use of compiler warnings is good practice and they should be enabled for all projects. On GCC and Clang `-Wall`, `-Wextra`, and `-Wpedantic` should be enabled, while `/W3` on MSVC.

With this, multiple warnings are generated when compiling: 
**MSCV**: 
 - `C4530`: Basically an MSVC-specific warning that one should add `/EHsc` to the compile flags. This is a simple CMake script fix.

**GCC**:
 - `-Wmisleading-indentation`: In Player.cpp there are a few `else` cases where the following line is indented with a tab. This is not really a misleading indentation problem and is mostly just a false positive on the compiler's part, but that tab should really be a set of spaces since that function is mostly indented with spaces. (Also the whole project's is completely mixed on tabs vs spaces. IMO as a separate issue this should be fixed.)
 - `-Wunused-variable`: Player.cpp:539 defines `int countLength = 0;` which is not used anywhere and should be deleted.

**Clang**:
 - `-Winconsistent-missing-override`: Descendants of the `Enemy` class seem to override virtual member functions such as `GetIntro()` and others like `ReturnDamage()` which come from `Entity`. These functions should be marked `override` but they are not. I guess the compiler figures out what you wanted to do, but this is really bad practice. Note that this is triggered even if one passes no arguments to clang while compiling, as in this is a default warning.
 - `-Wunused-private-field`: The Game class's `_Level` member is not used anywhere and should be deleted. (Also, identifiers starting with an underscore and then an upper case character (like `_Level`, or `_Player`) are reserved for implementations, and using them is undefined behavior)
 - `-Wreorder-ctor`: The member initializer list of SoundMaker class initializes members out of order. This is, iirc, UB, but most certainly nothing fun. Lines 77 and 76 should be swapped.

I can make a PR with these fixes if it is going to be considered.

**Comment by tagniam** [comment]
> ... the whole project's is completely mixed on tabs vs spaces. IMO as a separate issue this should be fixed.

> ... identifiers starting with an underscore and then an upper case character (like _Level, or _Player) are reserved for implementations, and using them is undefined behavior

I will soon be pushing out a code style change that will finally fix these issues once and for all. :) I previously opened an issue (#7) that tried to address this but I closed it due to inactivity.

Feel free to make a PR that fixes all the warnings you listed. As an extension, I would like to use these compiler warnings as part our Travis CI pipeline, let me know if you feel up to the task - otherwise, I'll create a separate issue for it.

**Comment by bodand** [comment]
OK, I'll create the PR in a few minutes. 

For the Travis CI pipeline, I have no idea as I never worked with Travis nor any CI really. In the past, I once tried using it, but it didn't really work out, so I can't say I'm up to that task. 
Also, I'd look into the new GitHub actions instead, because then you can keep development completely inside GitHub. But again, I never really tried either of them.

**Comment by bodand** [comment]
Oh, we already have a CI pipeline. I completely missed that. Then the CMake build should work with the warnings. As for detecting them, I have no idea.
