### ISSUE TITLE
Add item selling functionality

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#121]
The game currently allows the player to buy items from `Jeremy's Tool Store`, but the player cannot sell any items from their inventory to the store. We'd like to implement selling functionality in `Jeremy's Tool Store`. 

The player should be able to sell items at the same price they can be bought, for example since 1 bomb from the store costs 100 coins, the player should be able to sell 1 bomb from their invenyory for 100 coins.

**Comment by JerBast** [comment]
I would like to work on this, if possible.

**Comment by tagniam** [comment]
@JerBast Sure 👍
