### ISSUE TITLE
Create RandomEvent helper function

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#140]
Here is how we currently calculate random damage (from `GiantCrab.cpp`):
```c++
int GiantCrab::ReturnRiskAttackDamage() {
    int selector = Common::RandomInt(0, 5);
    switch(selector) {
    case 0:
    case 1:
    case 2:
    case 3:
        return 0;
        break;
    case 4:
    case 5:
        return 20;
        break;
    default:
        return 0;
        break;
    }
}
```

This basically means:
* 4/6 chance of doing 0 damage
* 2/6 chance of doing 20 damage

We'd like to create a helper method to avoid doing this. This is what I had in mind:

We'd have to create a function with the signature:
```c++
template<class T>
T RandomEvent(int denominator, vector<int> numerators, vector<T> outcomes)
```

where it must be that `sum(numerators) == denominator` and `numerators.size() == outcomes.size()`. The function takes in generic outcomes, so that even things like functions could be decided randomly.

With this helper function, the GiantCrab function could be rewritten as:
```c++
int GiantCrab::ReturnRiskAttackDamage() {
    // 4/6 chance of doing 0 damage
    // 2/6 chance of doing 20 damage

    int denominator = 6;
    vector<int> numerators{4, 2};
    vector<int> outcomes{0, 20};
    return RandomEvent<int>(denominator, numerators, outcomes);
}
```

This helper function should be placed in the `Common` class. If you have another design in mind, or know any existing STL libraries that can do this, let me know - we can probably do better than this :stuck_out_tongue:

**Comment by DJ73** [comment]
I'd like to work on this.
I'm sure that there might be better ways to do this depending from case to case but it sounds like a good solution for a generalised situation.
