### ISSUE TITLE
Crop screenshots

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#16]
The readme screenshots shouldn't show the Windows titlebars or scrollbars. There's also a weird red bar on the right of the battle screenshot that should also be cropped out.

**Comment by lamar-frankie** [comment]
I can work on this.

**Comment by IgorAntun** [comment]
Oh, I'm working on it already :(

**Comment by IgorAntun** [comment]
sorry, I forgot to comment here before starting. it's all yours if you want, though @lamar-frankie
