### ISSUE TITLE
Notify player when using non-existent item

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#34]
When a player attempts to use an item that is not in their inventory, currently the game doesn't do anything at all. 

Instead, there should be a message displayed that the item is not in the player's inventory, then call `Sleep(SLEEP_MS)` and redraw the screen.

**Comment by Shreya001** [comment]
Can I work on this?

**Comment by tagniam** [comment]
Yes you can @Shreya001!

**Comment by Mknsri** [comment]
Hey, I was thinking about working on this but looking at the code [here](https://github.com/tagniam/Turn/blob/master/Turn/src/Player.cpp#L163).

Is this already implemented?

**Comment by Shanmus4** [comment]
I have solved this issue please close it

**Comment by tagniam** [comment]
Closed by #41 and #44
