### ISSUE TITLE
Document enemy stats

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#35]
In the README there should be a sub-section under `How To Play` called `Enemy Types`. The documentation should follow this table template:

| Name          |  Attack Damage         | Risk Attack Damage | Healing Amount |
| ------------- |:----------------------:|:------------------:|:--------------:|
| Enemy 1       | 10-15                  | 20-25              | 10-15          |
| Enemy 2       | 10-15                  | 20-25              | 10-15          |

etc.

The `Crab`, `Giant Crab`, `Squid`, `Giant Squid`, and `Lich` enemy classes should be documented.
The attack/risk attack/healing points is documented in each enemy's corresponding `cpp` file.

**Comment by tenosiswono** [comment]
should we put ExperienceAmount and CoinsDrop too?

**Comment by tagniam** [comment]
@tenosiswono Good idea, you can add that in as well if you want to
