### ISSUE TITLE
Document player stats

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#36]
In the README there should be a sub-section under `How To Play` called `Player Classes`. The documentation should follow this table template:

| Name          |  Attack Damage         | Risk Attack Damage | Healing Amount |
| ------------- |:----------------------:|:------------------:|:--------------:|
| Player 1       | 10-15                  | 20-25              | 10-15          |
| Player 2       | 10-15                  | 20-25              | 10-15          |

etc.

The `Warrior`, `Rogue`, `Healer`, `Debugger`, and `Saitama` player classes should be documented.
The attack/risk attack/healing points is documented in each player's corresponding `cpp` file.

**Comment by tenosiswono** [comment]
I'll do it
