### ISSUE TITLE
Add item sound effects

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#39]
Edit: some sound effects are already implemented, like the sounds for attacking, bow and arrow attacks, and healing. However some sound effects are missing:

* Potion
* Bomb
* Whetstone
* Fleeing
* Buying things in the store
* Gambling
---

<del>The game would be a lot more fun with audio. In-game sound effects will be needed when the player uses the following items:</del>

<del>* Potion</del>
<del>* Whetstone</del>
<del>* Arrow</del>
<del>* Bomb</del>

<del>Make sure to credit where you get the sound effects from in the readme!</del>

**Comment by ArighnaIITG** [comment]
I am working on the issue..Give me some time..
