### ISSUE TITLE
Small game exit bug

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#43]
To reproduce this bug, start the game and choose `2) How To Play`, then `1) Quit`, then `3) Quit`. The game only quits once you choose `3` twice, when it should quit right away.

**Comment by kevinmmurphy** [comment]
I'd like to try this.

**Comment by tagniam** [comment]
Go ahead @kevinmmurphy !

**Comment by RamazanM** [comment]
Can you look for #46

**Comment by MediocreFred** [comment]
I'd like to give this a shot

**Comment by sarthi92** [comment]
In your game, the user has to press enter after every input. You can try using choice=getch() instead of cin >> choice
