### ISSUE TITLE
Implement an in-game store

### ISSUE THREAD

**Issue by tagniam** [tagniam/Turn#49]
This one should be fun!

What use are coins without things to buy? Using their coins, the player should be able to buy the items they need for battle in this store.

The price breakdown for the items should be as follows:
* 5 Arrows: 25 coins
* 1 Bomb: 100 coins
* 1 Potion: 150 coins
* 1 whetstone: 20 coins

In terms of the code, all the store functionality should be written inside `Store.cpp`. The player object is already passed in to the `StoreFront()` method as a starting point.

**Comment by sarthi92** [comment]
trying to implement this

**Comment by sarthi92** [comment]
one thing, will the store have unlimited supply of items?

**Comment by tagniam** [comment]
yes, for now at least.

**Comment by tagniam** [comment]
Closed by #53
