### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by ralismark** [tagniam/Turn#52]
It should be possible to make this game cross-platform. This would require using a different build system (e.g. CMake), as well as replacing uses of the windows API. From a brief view, it appears that it's only used for:

- console rendering
- input (with _getch)
- sleeping (easily replaceable with std::this_thread::sleep_for)

Console input/output could possibly be replaced with ncurses/pdcurses. Alternatively, ncurses could be used on Linux while still having windows API on windows with ifdef's.

**Comment by joealam** [comment]
I'm currently working on this and have it almost ready to go.

**Comment by tagniam** [comment]
Addressed by #57, #58 and #60. Thanks @joealam!
