### ISSUE TITLE
Do something with CMake's GLOB_RECURSE

### ISSUE THREAD

**Issue by isbodand** [tagniam/Turn#88]
As stated in the CMake [docs](https://cmake.org/cmake/help/latest/command/file.html#glob-recurse), it is unwise to use `GLOB_RECURSE` to find source files. 
And even worse if used as here, without `CONFIGURE_DEPENDS`, which should fix the problem of calling make ending up not recompiling some changed files.

I suggest adding at least `CONFIGURE_DEPENDS`, but it'd be better to add each file separately and manually when added to the project.

The latter requires some community approval, therefore, I wasn't planning on creating a PR until it is discussed which route to take if one is even taken.

**Comment by tagniam** [comment]
Interesting. Is there any alternative to manually adding new files in the CMake config files that does not depend on `GLOB_RECURSE`? Seems unwieldy.

**Comment by isbodand** [comment]
Sadly, not that I know of.

**Comment by BryanDiLaura** [comment]
The official recommendation from the CMake people is to avoid GLOB when possible. 

https://cmake.org/cmake/help/v3.15/command/file.html?highlight=glob#glob

The best practice seems to be using a list of sources, so CMake can tell when there are changes and it needs to rebuild the build system. I'd recommend moving to something along the lines of what lhiny's pull request does.

**Comment by isbodand** [comment]
@lhiny's pull request is actually perfectly done, it even uses modern CMake paradigms like target_* macros; therefore, I say we should just merge #91, even if we just have to add the new enemies in separate PR-s.
